import { createHash } from 'node:crypto'
import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { describe, expect, it } from 'vitest'
import { canonicalJson, lookHash, sha256Hex } from '../../shared/canonicalJson'

// Generated by OpenMontage (tests/lib/test_canonical_vectors.py, Task 0) with its real
// canonical_bytes/record_sha256 and copied here unchanged. Both repos pin the same bytes.
const CANONICAL_VECTORS_SHA256 = '4c1016d9b95628fd8a883347cde2b71fd3b4b06009f7d1d9a428e80e71865b98'
const VECTORS_PATH = resolve(__dirname, '../fixtures/lookSpec/vectors.json')
const raw = readFileSync(VECTORS_PATH)
const vectors = JSON.parse(raw.toString('utf8')) as {
  match: Array<{ name: string; input: unknown; canonical: string; sha256: string }>
  refuse: Array<{ name: string; input: unknown }>
}

describe('canonical JSON (OpenMontage-compatible subset)', () => {
  it('uses the vector file OpenMontage generated', () => {
    expect(createHash('sha256').update(raw).digest('hex')).toBe(CANONICAL_VECTORS_SHA256)
    expect(vectors.match.length).toBeGreaterThan(0)
    expect(vectors.refuse.length).toBeGreaterThan(0)
  })

  for (const vector of vectors.match) {
    it(`matches OpenMontage byte for byte: ${vector.name}`, () => {
      expect(canonicalJson(vector.input)).toBe(vector.canonical)
      expect(sha256Hex(canonicalJson(vector.input))).toBe(vector.sha256)
    })
  }

  for (const vector of vectors.refuse) {
    it(`refuses input outside the subset: ${vector.name}`, () => {
      expect(() => canonicalJson(vector.input)).toThrow()
    })
  }

  it('refuses non-finite numbers, lone surrogates and non-JSON values', () => {
    expect(() => canonicalJson(Number.NaN)).toThrow()
    expect(() => canonicalJson(Number.POSITIVE_INFINITY)).toThrow()
    expect(() => canonicalJson('\uD800')).toThrow()
    expect(() => canonicalJson({ when: new Date(0) })).toThrow()
    expect(() => canonicalJson([undefined])).toThrow()
    expect(() => canonicalJson(BigInt(1))).toThrow()
  })

  it('refuses two keys that become equal after NFC normalisation', () => {
    expect(() => canonicalJson({ ['café']: 1, ['café']: 2 })).toThrow()
  })

  it('omits object members whose value is undefined, as JSON does', () => {
    expect(canonicalJson({ a: 1, b: undefined })).toBe('{"a":1}')
  })

  it('sha256Hex agrees with node:crypto on UTF-8 input of many lengths', () => {
    for (const text of ['', 'abc', 'é日本\u{1F600}', 'x'.repeat(55), 'x'.repeat(56), 'x'.repeat(64), 'y'.repeat(1000)]) {
      expect(sha256Hex(text)).toBe(createHash('sha256').update(text, 'utf8').digest('hex'))
    }
  })

  it('lookHash is the sha256 of the canonical JSON', () => {
    const block = vectors.match.find(vector => vector.name === 'look-character-1.1')!
    expect(lookHash(block.input)).toBe(block.sha256)
  })
})
