// Canonical JSON and SHA-256 for look hashes.
//
// look_hash must equal OpenMontage's record_sha256 (lib/canonical_json.py) byte
// for byte. This is the OpenMontage-compatible subset of RFC 8785: strings
// (keys and values) NFC-normalised, keys sorted by UTF-16 code units, JCS string
// escapes, ES6 number formatting, no whitespace. Anything outside the subset
// throws instead of hashing: non-finite numbers, integers beyond the JS safe
// range (OpenMontage prints big Python ints as digits; JS cannot represent them),
// lone surrogates, and values JSON cannot carry. Pinned by
// tests/fixtures/lookSpec/vectors.json, generated by OpenMontage.
//
// Runs in the browser and on the server, so SHA-256 is implemented here rather
// than taken from node:crypto.

export class CanonicalJsonError extends Error {}

const SHORT_ESCAPES: Record<string, string> = {
  '\b': '\\b',
  '\t': '\\t',
  '\n': '\\n',
  '\f': '\\f',
  '\r': '\\r',
  '"': '\\"',
  '\\': '\\\\',
}

function escapeString(value: string): string {
  if (/[\uD800-\uDBFF](?![\uDC00-\uDFFF])|(?<![\uD800-\uDBFF])[\uDC00-\uDFFF]/.test(value)) {
    throw new CanonicalJsonError('A string contains a lone surrogate and cannot be hashed.')
  }
  let out = '"'
  for (const ch of value.normalize('NFC')) {
    const short = SHORT_ESCAPES[ch]
    if (short !== undefined) out += short
    else if (ch.charCodeAt(0) < 0x20) out += `\\u${ch.charCodeAt(0).toString(16).padStart(4, '0')}`
    else out += ch
  }
  return `${out}"`
}

function formatNumber(value: number): string {
  if (!Number.isFinite(value)) throw new CanonicalJsonError('NaN and Infinity cannot be hashed.')
  if (Number.isInteger(value) && !Number.isSafeInteger(value)) {
    throw new CanonicalJsonError(`The number ${value} is outside the safe integer range and cannot be hashed.`)
  }
  return Object.is(value, -0) ? '0' : String(value)
}

function isPlainObject(value: unknown): value is Record<string, unknown> {
  if (typeof value !== 'object' || value === null) return false
  const prototype = Object.getPrototypeOf(value)
  return prototype === Object.prototype || prototype === null
}

function serialize(value: unknown, out: string[]): void {
  if (value === null) {
    out.push('null')
  } else if (value === true || value === false) {
    out.push(String(value))
  } else if (typeof value === 'number') {
    out.push(formatNumber(value))
  } else if (typeof value === 'string') {
    out.push(escapeString(value))
  } else if (Array.isArray(value)) {
    out.push('[')
    value.forEach((item, index) => {
      if (item === undefined) throw new CanonicalJsonError('Arrays cannot hold undefined.')
      if (index) out.push(',')
      serialize(item, out)
    })
    out.push(']')
  } else if (isPlainObject(value)) {
    const entries: Array<[string, unknown]> = []
    const seen = new Set<string>()
    for (const [key, member] of Object.entries(value)) {
      if (member === undefined) continue
      const normalized = key.normalize('NFC')
      if (seen.has(normalized)) throw new CanonicalJsonError(`Two keys are the same after normalisation: ${normalized}`)
      seen.add(normalized)
      entries.push([normalized, member])
    }
    // Default string comparison is by UTF-16 code units, which is what JCS requires.
    entries.sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0))
    out.push('{')
    entries.forEach(([key, member], index) => {
      if (index) out.push(',')
      out.push(escapeString(key), ':')
      serialize(member, out)
    })
    out.push('}')
  } else {
    throw new CanonicalJsonError(`A ${typeof value} value cannot be hashed.`)
  }
}

export function canonicalJson(value: unknown): string {
  const out: string[] = []
  serialize(value, out)
  return out.join('')
}

const K = new Uint32Array([
  0x428a2f98, 0x71374491, 0xb5c0fbcf, 0xe9b5dba5, 0x3956c25b, 0x59f111f1, 0x923f82a4, 0xab1c5ed5,
  0xd807aa98, 0x12835b01, 0x243185be, 0x550c7dc3, 0x72be5d74, 0x80deb1fe, 0x9bdc06a7, 0xc19bf174,
  0xe49b69c1, 0xefbe4786, 0x0fc19dc6, 0x240ca1cc, 0x2de92c6f, 0x4a7484aa, 0x5cb0a9dc, 0x76f988da,
  0x983e5152, 0xa831c66d, 0xb00327c8, 0xbf597fc7, 0xc6e00bf3, 0xd5a79147, 0x06ca6351, 0x14292967,
  0x27b70a85, 0x2e1b2138, 0x4d2c6dfc, 0x53380d13, 0x650a7354, 0x766a0abb, 0x81c2c92e, 0x92722c85,
  0xa2bfe8a1, 0xa81a664b, 0xc24b8b70, 0xc76c51a3, 0xd192e819, 0xd6990624, 0xf40e3585, 0x106aa070,
  0x19a4c116, 0x1e376c08, 0x2748774c, 0x34b0bcb5, 0x391c0cb3, 0x4ed8aa4a, 0x5b9cca4f, 0x682e6ff3,
  0x748f82ee, 0x78a5636f, 0x84c87814, 0x8cc70208, 0x90befffa, 0xa4506ceb, 0xbef9a3f7, 0xc67178f2,
])

/** Hex SHA-256 of the UTF-8 encoding of `text`. */
export function sha256Hex(text: string): string {
  const data = new TextEncoder().encode(text)
  const bitLength = data.length * 8
  const padded = new Uint8Array(Math.ceil((data.length + 9) / 64) * 64)
  padded.set(data)
  padded[data.length] = 0x80
  const view = new DataView(padded.buffer)
  view.setUint32(padded.length - 8, Math.floor(bitLength / 0x100000000))
  view.setUint32(padded.length - 4, bitLength >>> 0)

  const h = new Uint32Array([0x6a09e667, 0xbb67ae85, 0x3c6ef372, 0xa54ff53a, 0x510e527f, 0x9b05688c, 0x1f83d9ab, 0x5be0cd19])
  const w = new Uint32Array(64)
  const rotr = (x: number, n: number) => (x >>> n) | (x << (32 - n))
  for (let offset = 0; offset < padded.length; offset += 64) {
    for (let i = 0; i < 16; i++) w[i] = view.getUint32(offset + i * 4)
    for (let i = 16; i < 64; i++) {
      const s0 = rotr(w[i - 15], 7) ^ rotr(w[i - 15], 18) ^ (w[i - 15] >>> 3)
      const s1 = rotr(w[i - 2], 17) ^ rotr(w[i - 2], 19) ^ (w[i - 2] >>> 10)
      w[i] = (w[i - 16] + s0 + w[i - 7] + s1) >>> 0
    }
    let [a, b, c, d, e, f, g, hh] = h
    for (let i = 0; i < 64; i++) {
      const s1 = rotr(e, 6) ^ rotr(e, 11) ^ rotr(e, 25)
      const ch = (e & f) ^ (~e & g)
      const t1 = (hh + s1 + ch + K[i] + w[i]) >>> 0
      const s0 = rotr(a, 2) ^ rotr(a, 13) ^ rotr(a, 22)
      const maj = (a & b) ^ (a & c) ^ (b & c)
      const t2 = (s0 + maj) >>> 0
      hh = g
      g = f
      f = e
      e = (d + t1) >>> 0
      d = c
      c = b
      b = a
      a = (t1 + t2) >>> 0
    }
    h[0] += a
    h[1] += b
    h[2] += c
    h[3] += d
    h[4] += e
    h[5] += f
    h[6] += g
    h[7] += hh
  }
  return Array.from(h, word => word.toString(16).padStart(8, '0')).join('')
}

/** look_hash: sha256 of the canonical JSON of a validated look block (= OpenMontage record_sha256). */
export function lookHash(validatedSpec: unknown): string {
  return sha256Hex(canonicalJson(validatedSpec))
}
